### ISSUE TITLE
support fromParam() function for workloadSetting reading from Param which could come from AppConfig

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/oam-go-sdk#16]
```
apiVersion: core.oam.dev/v1alpha1
kind: Component
metadata:
  name: example
spec:
  paramerters:
      - name: framwork
         type: string
         default: java
  workloadType: oam.aliyun.com/v1alpha1.Workload
  workloadSettings:
    language: JavaScript
    framework: "fromParam[framwork]"
```

We should have common function call to help.
